project:
  type: website
  output-dir: _site
  resources:
    - old_html/**
    - assets/js/theme.js

execute:
  freeze: auto

website:
  title: "Patrick Sch√§fer"
  site-url: "https://patrickzib.github.io/"
  repo-url: "https://github.com/patrickzib/patrickzib.github.io"
  description: "Senior researcher in time series analytics, similarity search, and data management."
  page-navigation: false

format:
  html:
    theme: default
    css:
      - assets/css/main.css
      - assets/css/academicons.css
      - assets/css/academicons.min.css
      - assets/css/collapse.css
      - styles.scss
    toc: false
    include-before-body:
      - partials/masthead.html
      - partials/sidebar-open.html
    include-after-body:
      - partials/sidebar-close.html
      - partials/scripts.html
